[package]
name = "symbolic-llvm"
version = "0.1.0"
authors = ["Henning Günther <raptamei.pi@gmail.com>"]

[dependencies]
num-bigint = "0.1"
num-traits = "0.1"
smtrs = { git = "https://github.com/hguenther/smtrs" }
llvm-ir = { git = "https://github.com/hguenther/llvm-ir" }